// GET SHOPPING CART
export const GET_SHOPPINGCART_PENDING = "GET_SHOPPINGCART_PENDING";
export const GET_SHOPPINGCART_SUCCESS = "GET_SHOPPINGCART_SUCCESS";
export const GET_SHOPPINGCART_FAILURE = "GET_SHOPPINGCART_FAILURE";

// ADD TO SHOPPINGCART
export const ADD_ITEM_TO_SHOPPINGCART_PENDING =
  "ADD_ITEM_TO_SHOPPINGCART_PENDING";
export const ADD_ITEM_TO_SHOPPINGCART_SUCCESS =
  "ADD_ITEM_TO_SHOPPINGCART_SUCCESS";
export const ADD_ITEM_TO_SHOPPINGCART_FAILURE =
  "ADD_ITEM_TO_SHOPPINGCART_FAILURE";

// REMOVE FROM SHOPPINGCART
export const REMOVE_ITEM_FROM_SHOPPINGCART_PENDING =
  "REMOVE_ITEM_FROM_SHOPPINGCART_PENDING";
export const REMOVE_ITEM_FROM_SHOPPINGCART_SUCCESS =
  "REMOVE_ITEM_FROM_SHOPPINGCART_SUCCESS";
export const REMOVE_ITEM_FROM_SHOPPINGCART_FAILURE =
  "REMOVE_ITEM_FROM_SHOPPINGCART_FAILURE";

// CLEAR SHOPPING CART
export const CLEAR_SHOPPINGCART = "CLEAR_SHOPPINGCART";
export const CLEAR_SHOPPINGCART_PENDING = "CLEAR_SHOPPINGCART_PENDING";
export const CLEAR_SHOPPINGCART_SUCCESS = "CLEAR_SHOPPINGCART_SUCCESS";
export const CLEAR_SHOPPINGCART_FAILURE = "CLEAR_SHOPPINGCART_FAILURE";

export const CLEAR_SHOPPINGCART_LOCALLY = "CLEAR_SHOPPINGCART_LOCALLY";

//TOGGLE SHOPPINGCART MENU/SIDEBAR
export const TOGGLE_CART = "TOGGLE_CART";
