export const ADD_ITEM_TO_SHOPPINGCART_PENDING =
  "ADD_ITEM_TO_SHOPPINGCART_PENDING";
export const ADD_ITEM_TO_SHOPPINGCART_SUCCESS =
  "ADD_ITEM_TO_SHOPPINGCART_SUCCESS";
export const ADD_ITEM_TO_SHOPPINGCART_FAILURE =
  "ADD_ITEM_TO_SHOPPINGCART_FAILURE";
export const REMOVE_ITEM_FROM_SHOPPINGCART = "REMOVE_ITEM_FROM_SHOPPINGCART";
export const TOGGLE_CART = "TOGGLE_CART";
