// GET SHOPPING CART
export const GET_SHOPPINGCART_PENDING = "GET_SHOPPINGCART_PENDING";
export const GET_SHOPPINGCART_SUCCESS = "GET_SHOPPINGCART_SUCCESS";
export const GET_SHOPPINGCART_FAILURE = "GET_SHOPPINGCART_FAILURE";

// ADD TO SHOPPINGCART
export const ADD_ITEM_TO_SHOPPINGCART_PENDING =
  "ADD_ITEM_TO_SHOPPINGCART_PENDING";
export const ADD_ITEM_TO_SHOPPINGCART_SUCCESS =
  "ADD_ITEM_TO_SHOPPINGCART_SUCCESS";
export const ADD_ITEM_TO_SHOPPINGCART_FAILURE =
  "ADD_ITEM_TO_SHOPPINGCART_FAILURE";
export const REMOVE_ITEM_FROM_SHOPPINGCART = "REMOVE_ITEM_FROM_SHOPPINGCART";

//TOGGLE SHOPPINGCART MENU/SIDEBAR
export const TOGGLE_CART = "TOGGLE_CART";
